name: Release
on:
  push:
    tags:
      - '*'
jobs:
  goreleaser:
    name: GoReleaser
    runs-on:
      - ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.14
      - name: Install webkit and gtk
        run: sudo apt-get install libwebkit2gtk-4.0-dev libgtk-3-dev
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'